### ISSUE TITLE
stdout not getting piped to file

### ISSUE THREAD

**Issue by sarich** [ACME-Climate/CMDV-testing#9]
```
cmdvVersion: v1.0
class: TestWorkflow
label: Hello World Example
steps:
  deploy: none
  run:
    label: hello world
    run:
      stdout: hello_world.out
      stderr: hello_world.err
      baseCommand: ['echo Hello World!']
      out:
        log:
          type: File
          glob: hello_world.out
```
No hello_world.out file is written
